import { createReadStream } from 'node:fs';
import { stat } from 'node:fs/promises';
import path from 'node:path';
import { Readable } from 'node:stream';
import { UPLOAD_DIR } from '@/lib/media/store';

export const runtime = 'nodejs';

/**
 * Serves user uploads and generated images from disk.
 *
 * This route exists because `public/` cannot do the job: Next snapshots that
 * directory at server start, so a runtime-written file 404s until a restart
 * (see the comment in src/lib/media/store.ts — verified, not assumed).
 */

const CONTENT_TYPES: Record<string, string> = {
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.webp': 'image/webp',
  '.gif': 'image/gif',
};

/**
 * Names are generated by us as `<uuid>.<ext>`, so anything else is either a
 * bug or an attack. Validating the shape — rather than trying to sanitise an
 * arbitrary string — is what makes path traversal impossible here: `..` and
 * `/` simply cannot match.
 */
const NAME_RE = /^[a-f0-9-]{36}\.(png|jpg|webp|gif)$/;

export async function GET(_request: Request, { params }: { params: Promise<{ name: string }> }) {
  const { name } = await params;
  if (!NAME_RE.test(name)) return new Response('Not found', { status: 404 });

  const filePath = path.join(UPLOAD_DIR, name);

  try {
    const info = await stat(filePath);
    if (!info.isFile()) return new Response('Not found', { status: 404 });

    const stream = Readable.toWeb(createReadStream(filePath)) as ReadableStream;
    return new Response(stream, {
      headers: {
        'Content-Type': CONTENT_TYPES[path.extname(name)] ?? 'application/octet-stream',
        'Content-Length': String(info.size),
        // Content-addressed by a random name: a given URL's bytes never change.
        'Cache-Control': 'public, max-age=31536000, immutable',
      },
    });
  } catch {
    return new Response('Not found', { status: 404 });
  }
}
