/**
 * Writes the live taxonomy back out as an idempotent seed migration.
 *
 *   npx tsx scripts/export-taxonomy.ts [--out=drizzle/0038_taxonomy_seed.sql]
 *
 * ## Why this exists
 *
 * The taxonomy is the most researched data in this product and it lives in
 * exactly one place: the production database. `drizzle/0003_uk_taxonomy_*.sql`
 * is 34 lines of pure DDL with **zero inserts** — the 20 categories' UK market
 * context and all 103 sectors were backfilled out of band from
 * `sql/freelee-marketplace-ready-data.sql`, a file that is not in this
 * repository and not on this server. `src/db/seed.ts` seeds eight *different*
 * categories with different slugs, so it does not fill the gap either.
 *
 * A fresh install therefore produces 20 categories with every UK column NULL
 * and **no sectors at all**. Months of curation survive only as long as one
 * database does. This turns it back into a file.
 *
 * Builds its own Drizzle client rather than importing the `server-only`-guarded
 * `@/db`, the same reason `scripts/export-bundle.ts` and `src/db/seed.ts` do.
 *
 * ## Why the output looks the way it does
 *
 * Everything is matched on a **natural key**, never on an id: categories by
 * `slug`, sectors by `(category slug, sector slug)`, audience links by
 * `(category slug, segment code)`. The live ids run 29–48 for categories, so
 * an id-keyed dump would be worthless on any other database — and category ids
 * are load-bearing (`markSpec` picks a persona card's cell shape from
 * `categories.id`), so they must not be forced either.
 *
 * `ON CONFLICT … DO UPDATE` rather than `DO NOTHING`: re-running this against a
 * database that already has the taxonomy should *correct* it, which is what
 * makes it a restore rather than a first-install-only seed.
 */
import 'dotenv/config';
import { config } from 'dotenv';
import { writeFile } from 'node:fs/promises';
import { drizzle } from 'drizzle-orm/postgres-js';
import { asc } from 'drizzle-orm';
import postgres from 'postgres';
import * as schema from '../src/db/schema';

config({ path: '.env.local', quiet: true });

function arg(name: string): string | undefined {
  const prefix = `--${name}=`;
  return process.argv.find((a) => a.startsWith(prefix))?.slice(prefix.length);
}

/** Postgres string literal. Doubling the quote is the only escape it needs. */
function q(value: string | null | undefined): string {
  if (value === null || value === undefined) return 'NULL';
  return `'${value.replace(/'/g, "''")}'`;
}

function jsonb(value: unknown[]): string {
  return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
}

function n(value: number | null | undefined): string {
  return value === null || value === undefined ? 'NULL' : String(value);
}

async function main() {
  const connectionString = process.env.DATABASE_URL;
  if (!connectionString) {
    console.error('DATABASE_URL is not set.');
    process.exit(1);
  }

  const sql = postgres(connectionString, { max: 1 });
  const db = drizzle(sql, { schema });

  const categories = await db.select().from(schema.categories).orderBy(asc(schema.categories.position));
  const sectors = await db.select().from(schema.sectors).orderBy(asc(schema.sectors.categoryId), asc(schema.sectors.position));

  // The link table may not exist yet on a database that has not run 0037.
  let audiences: { categoryId: number; segmentCode: string; note: string | null; position: number }[] = [];
  try {
    audiences = await db.select().from(schema.categoryAudienceSegments);
  } catch {
    console.warn('category_audience_segments not found — skipping audience links.');
  }

  const slugOf = new Map(categories.map((c) => [c.id, c.slug]));
  const out: string[] = [];

  out.push(`-- The UK taxonomy, as data.
--
-- GENERATED by scripts/export-taxonomy.ts — do not hand-edit; regenerate it.
-- Exported ${new Date().toISOString().slice(0, 10)} from the live database:
-- ${categories.length} categories, ${sectors.length} sectors, ${audiences.length} audience links.
--
-- This file exists because the taxonomy had no source outside one database.
-- 0003 created the tables and inserted nothing; the curated dump it was
-- backfilled from is not in this repository. Everything below is matched on a
-- natural key rather than an id, because live category ids start at 29 and are
-- load-bearing (a persona card's cell shape is picked from categories.id), so
-- they must be neither assumed nor forced.
--
-- Safe to re-run: conflicts UPDATE, so this restores a drifted taxonomy rather
-- than only seeding an empty one.
`);

  out.push('\n-- ============================ Categories ============================\n');
  for (const c of categories) {
    out.push(`INSERT INTO "categories" ("name", "slug", "description", "color", "is_active", "position",
  "uk_market_size", "uk_growth_rate", "uk_key_regulations", "uk_industry_bodies", "default_risk_level", "narrative_potential")
VALUES (${q(c.name)}, ${q(c.slug)}, ${q(c.description)}, ${q(c.color)}, ${c.isActive}, ${c.position},
  ${q(c.ukMarketSize)}, ${q(c.ukGrowthRate)}, ${jsonb(c.ukKeyRegulations)}, ${jsonb(c.ukIndustryBodies)}, ${q(c.defaultRiskLevel)}, ${q(c.narrativePotential)})
ON CONFLICT ("slug") DO UPDATE SET
  "name" = EXCLUDED."name", "description" = EXCLUDED."description", "color" = EXCLUDED."color",
  "position" = EXCLUDED."position", "uk_market_size" = EXCLUDED."uk_market_size",
  "uk_growth_rate" = EXCLUDED."uk_growth_rate", "uk_key_regulations" = EXCLUDED."uk_key_regulations",
  "uk_industry_bodies" = EXCLUDED."uk_industry_bodies", "default_risk_level" = EXCLUDED."default_risk_level",
  "narrative_potential" = EXCLUDED."narrative_potential";\n`);
  }

  out.push('\n-- ============================== Sectors =============================\n');
  for (const s of sectors) {
    const parent = slugOf.get(s.categoryId);
    if (!parent) continue; // orphan row — cannot be restored without its category
    out.push(`INSERT INTO "sectors" ("category_id", "code", "name", "slug", "description",
  "b2c_suitability", "b2b_suitability", "b2g_suitability", "typical_risk_level", "narrative_fit",
  "primary_interaction_modes", "is_active", "position")
SELECT c."id", ${q(s.code)}, ${q(s.name)}, ${q(s.slug)}, ${q(s.description)},
  ${s.b2cSuitability}, ${s.b2bSuitability}, ${s.b2gSuitability}, ${q(s.typicalRiskLevel)}, ${q(s.narrativeFit)},
  ${jsonb(s.primaryInteractionModes)}, ${s.isActive}, ${s.position}
FROM "categories" c WHERE c."slug" = ${q(parent)}
ON CONFLICT ("category_id", "slug") DO UPDATE SET
  "code" = EXCLUDED."code", "name" = EXCLUDED."name", "description" = EXCLUDED."description",
  "b2c_suitability" = EXCLUDED."b2c_suitability", "b2b_suitability" = EXCLUDED."b2b_suitability",
  "b2g_suitability" = EXCLUDED."b2g_suitability", "typical_risk_level" = EXCLUDED."typical_risk_level",
  "narrative_fit" = EXCLUDED."narrative_fit", "primary_interaction_modes" = EXCLUDED."primary_interaction_modes",
  "is_active" = EXCLUDED."is_active", "position" = EXCLUDED."position";\n`);
  }

  if (audiences.length > 0) {
    out.push('\n-- ========================= Audience links ==========================\n');
    for (const a of audiences) {
      const parent = slugOf.get(a.categoryId);
      if (!parent) continue;
      out.push(`INSERT INTO "category_audience_segments" ("category_id", "segment_code", "note", "position")
SELECT c."id", ${q(a.segmentCode)}, ${q(a.note)}, ${a.position}
FROM "categories" c WHERE c."slug" = ${q(parent)}
ON CONFLICT ("category_id", "segment_code") DO UPDATE SET
  "note" = EXCLUDED."note", "position" = EXCLUDED."position";\n`);
    }
  }

  const target = arg('out') ?? 'drizzle/0038_taxonomy_seed.sql';
  await writeFile(target, out.join(''), 'utf8');
  await sql.end();

  console.log(`Wrote ${target}`);
  console.log(`  ${categories.length} categories, ${sectors.length} sectors, ${audiences.length} audience links`);
}

main().then(
  () => process.exit(0),
  (error) => { console.error(error); process.exit(1); },
);
