/**
 * Imports a translations export (scripts/export-translations.ts's output —
 * or a hand-edited/coworker-reviewed copy of one) back into the database.
 * Upserts on the real unique constraint (namespace, key, locale), so
 * re-running is always safe — never duplicates, always just overwrites with
 * whatever the file says. Dry-run by default, matching this project's other
 * import script (scripts/import-bundle.ts, Phase 8).
 *
 *   npx tsx scripts/import-translations.ts --file=i18n/translations-export.json [--apply]
 */
import 'dotenv/config';
import { readFile } from 'node:fs/promises';
import { drizzle } from 'drizzle-orm/postgres-js';
import postgres from 'postgres';
import * as schema from '../src/db/schema';
import { translations } from '../src/db/schema';

type ExportedRow = { namespace: string; key: string; locale: string; value: string };

function arg(name: string): string | undefined {
  const prefix = `--${name}=`;
  return process.argv.find((a) => a.startsWith(prefix))?.slice(prefix.length);
}

async function main() {
  const filePath = arg('file');
  const apply = process.argv.includes('--apply');
  if (!filePath) {
    console.error('Usage: npx tsx scripts/import-translations.ts --file=path.json [--apply]');
    process.exit(1);
  }

  const rows: ExportedRow[] = JSON.parse(await readFile(filePath, 'utf8'));
  const badRow = rows.find((r) => !r.namespace || !r.key || !r.locale || typeof r.value !== 'string');
  if (badRow) throw new Error(`Malformed row (needs namespace/key/locale/value): ${JSON.stringify(badRow)}`);
  if (rows.some((r) => r.locale === 'en')) {
    throw new Error('File contains locale="en" rows — English is never stored in translations (see docs/17-translations.md); check the file was generated by this project\'s own export script.');
  }

  console.log(`${apply ? 'Applying' : 'Dry run (pass --apply to write)'}: ${rows.length} row(s) from ${filePath}`);
  if (!apply) {
    for (const row of rows.slice(0, 10)) console.log(`  would upsert: ${row.namespace}.${row.key} [${row.locale}] = "${row.value}"`);
    if (rows.length > 10) console.log(`  … and ${rows.length - 10} more`);
    return;
  }

  const connectionString = process.env.DATABASE_URL;
  if (!connectionString) throw new Error('DATABASE_URL is not set.');
  const client = postgres(connectionString, { max: 1 });
  const db = drizzle(client, { schema });

  let upserted = 0;
  for (const row of rows) {
    await db
      .insert(translations)
      .values(row)
      .onConflictDoUpdate({
        target: [translations.namespace, translations.key, translations.locale],
        set: { value: row.value, updatedAt: new Date() },
      });
    upserted += 1;
  }

  console.log(`Applied — ${upserted} row(s) upserted.`);
  await client.end();
}

main().catch((error) => {
  console.error('Import failed:', error);
  process.exit(1);
});
